# Example configuration for the Miro backend service
# Copy to `config.yaml` and adjust values for your environment.
database_url: sqlite:///./app.db
cors_origins:
  - "https://example.com"
client_id: your-client-id
client_secret: your-client-secret
webhook_secret: change-me
oauth_auth_base: https://miro.com/oauth/authorize
oauth_token_url: https://api.miro.com/v1/oauth/token
oauth_scope: boards:read boards:write
oauth_redirect_uri: https://example.com/oauth/callback
logfire_service_name: miro-backend
logfire_send_to_logfire: false
http_timeout_seconds: 10.0
