version: "3.9"

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./config:/app/config
      - sqlite_data:/data
    environment:
      - MIRO_DATABASE_URL=sqlite:////data/app.db

  client:
    build: ./web/client
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  sqlite_data:
