# Example configuration for the Miro backend service
# Copy to `config.yaml` and adjust values for your environment.
database_url: sqlite:///./app.db
cors_origins:
  - "https://example.com"  # Explicit origins; avoid "*" in production
client_id: your-client-id
client_secret: your-client-secret
webhook_secret: change-me
oauth_auth_base: https://miro.com/oauth/authorize  # Base URL for OAuth authorisation
oauth_token_url: https://api.miro.com/v1/oauth/token  # OAuth token endpoint
oauth_scope: boards:read boards:write  # OAuth scopes requested
oauth_redirect_uri: https://example.com/oauth/callback  # OAuth callback URL
logfire_service_name: miro-backend
logfire_send_to_logfire: false
http_timeout_seconds: 10.0  # HTTP client timeout for Miro API calls
idempotency_cleanup_seconds: 86400  # Interval between idempotency cleanup runs
encryption_key: ""  # Base64-encoded 32-byte key for encrypting tokens (optional)
