name: CI

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      # Enable Corepack to use Yarn 4
      - run: corepack enable

      - name: Install dependencies
        run: npm install --frozen-lockfile || npm install

      - name: Run Prettier check
        run: npm run prettier:check

      - name: Run ESLint
        run: npm run lint

      - name: Build
        run: npm run build
