name: ci

on:
  push:
  pull_request:

jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'
          cache-dependency-path: pyproject.toml
      - name: Install dependencies
        run: pip install .[dev]
      - name: Run pre-commit
        run: pre-commit run --files $(git ls-files)
      - name: Run tests
        run: pytest

  node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: web/client/package-lock.json
      - name: Install dependencies
        run: npm ci
        working-directory: web/client
      - name: Run tests
        run: npm test
        working-directory: web/client
      - name: Lint
        run: npm run lint
        working-directory: web/client
      - name: Build
        run: npm run build
        working-directory: web/client
