name: Commitlint
permissions:
  contents: read

on:
  pull_request:
    types: [opened, synchronize, edited]

env:
  NODE_VERSION: 24

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      - run: corepack enable
      - run: npm ci --prefer-offline --no-audit
      - run:
          npx commitlint --from=${{ github.event.pull_request.base.sha }}
          --to=${{ github.event.pull_request.head.sha }}
