name: miro-dotnet

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main, develop]

permissions: write-all

env:
  NODE_VERSION: 20
  DOTNET_VERSION: "9.0.x"

jobs:
  dotnet-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Format check
        run: dotnet format --no-restore --verify-no-changes fenrick.miro.server/fenrick.miro.server.csproj

  dotnet-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Restore
        run: dotnet restore fenrick.miro.tests/fenrick.miro.tests.csproj
      - name: Test
        run: dotnet test fenrick.miro.tests/fenrick.miro.tests.csproj
