name: miro-unit-tests

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main, develop]

permissions: write-all

env:
  NODE_VERSION: 20
  DOTNET_VERSION: "9.0.x"

jobs:
  node-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: fenrick.miro.client/package-lock.json
      - run: corepack enable
        working-directory: fenrick.miro.client
      - run: npm ci --prefer-offline --no-audit
        working-directory: fenrick.miro.client
      - name: Node tests
        run: npm run test
        working-directory: fenrick.miro.client
      - name: Upload coverage
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: fenrick.miro.client/coverage/*
          include-hidden-files: true
          retention-days: 1

  dotnet-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Restore
        run: dotnet restore fenrick.miro.tests/fenrick.miro.tests.csproj
      - name: Test
        run: dotnet test fenrick.miro.tests/fenrick.miro.tests.csproj
