name: python-tests

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install fastapi "uvicorn[standard]" pydantic sqlalchemy alembic pytest pytest-cov pytest-asyncio httpx
      - name: Run tests
        run: pytest
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: python-coverage
          path: coverage.xml
