name: repo-commitlint
permissions:
  contents: read

on:
  pull_request:
    types: [opened, synchronize, edited]

env:
  NODE_VERSION: 20

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: fenrick.miro.client/package-lock.json
      - run: corepack enable
        working-directory: fenrick.miro.client
      - run: npm ci --prefer-offline --no-audit
        working-directory: fenrick.miro.client
      - run:
          npx commitlint --from=${{ github.event.pull_request.base.sha }} --to=${{ github.event.pull_request.head.sha }}
        working-directory: fenrick.miro.client
