name: repo-sonar

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions: write-all

env:
  NODE_VERSION: 20

jobs:
  repo-sonar:
    runs-on: windows-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: "zulu"
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Node & install front-end deps
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: fenrick.miro.client/package-lock.json
      - run: corepack enable && npm ci
        working-directory: fenrick.miro.client
      - name: Run node unit tests
        run: npm run test
        working-directory: fenrick.miro.client
      - name: Begin sonar-scanner
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: powershell
        run: |
          .\.sonar\scanner\dotnet-sonarscanner begin `
            /k:"fenrick_MiroDiagraming" /o:"fenrick" `
            /d:sonar.token="${{ secrets.SONAR_TOKEN }}" `
            /d:sonar.host.url="https://sonarcloud.io" `
            /d:sonar.javascript.lcov.reportPaths="${{ github.workspace }}/fenrick.miro.client/coverage/lcov.info"
      - name: End sonar-scanner
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: powershell
        run: |
          .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
