name: server-build

on:
  push:

permissions: write-all

env:
  NODE_VERSION: 20
  DOTNET_VERSION: "9.0.x"

jobs:
  server-build:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: restore
        run: dotnet restore fenrick.miro.slnx
      - name: build
        run: dotnet build fenrick.miro.slnx
