name: server-tests

on:
  push:
  pull_request:

permissions: write-all

env:
  NODE_VERSION: 20
  DOTNET_VERSION: "9.0.x"

jobs:
  dotnet-tests:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Restore
        run: dotnet restore fenrick.miro.tests/fenrick.miro.tests.csproj
      - name: Test
        run: dotnet test fenrick.miro.tests/fenrick.miro.tests.csproj
